name: github_user_search
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:  
  dio: ^5.4.3+1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  #injectable: ^2.3.5  
  json_annotation: ^4.9.0  
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_gen_runner:
  #injectable_generator: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - .env
